# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entrypoints
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

# Log configuration
log:
  level: "DEBUG"

# Access log configuration
accessLog: {}

# Docker provider configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
